export default function Terms() {
  return (
    <div className="max-w-4xl mx-auto px-6 py-12 text-gray-800 dark:text-gray-300">
      <h1 className="text-3xl font-bold mb-6">Terms & Conditions</h1>

      <p className="mb-4">
        By using our document tampering detection system, you agree to the following terms and conditions.
      </p>

      <h2 className="text-xl font-semibold mt-6 mb-2">1. Usage</h2>
      <p className="mb-4">
        This platform is designed for educational and verification purposes. Users must not misuse the system for illegal activities.
      </p>

      <h2 className="text-xl font-semibold mt-6 mb-2">2. Accuracy</h2>
      <p className="mb-4">
        While we use multiple verification layers, results are probabilistic and should not be considered legally binding.
      </p>

      <h2 className="text-xl font-semibold mt-6 mb-2">3. Data Handling</h2>
      <p className="mb-4">
        Uploaded files are processed temporarily and may be deleted automatically after analysis.
      </p>

      <h2 className="text-xl font-semibold mt-6 mb-2">4. Liability</h2>
      <p>
        We are not responsible for decisions made based on the results generated by this system.
      </p>
    </div>
  );
}